"use strict";
var ACTION;
(function (ACTION) {
    ACTION[ACTION["SIGN_IN"] = 1001] = "SIGN_IN";
    ACTION[ACTION["SIGN_OUT"] = 1002] = "SIGN_OUT";
    ACTION[ACTION["FETCH_PRODUCT_LIST"] = 1003] = "FETCH_PRODUCT_LIST";
    ACTION[ACTION["SIGN_UP"] = 1004] = "SIGN_UP";
    ACTION[ACTION["FETCH_LOCATION_LIST"] = 2001] = "FETCH_LOCATION_LIST";
})(ACTION = exports.ACTION || (exports.ACTION = {}));
//# sourceMappingURL=ACTION.js.map